### ISSUE TITLE
isSame() is broken

### ISSUE THREAD

**Issue by johnfumaster** [spencermountain/spacetime#173]
**How to reproduce**
```
const s = spacetime([2017, 5, 2]);
s.isSame('2017, 5, 2', 'millisecond')
```

**Error returned**
```
TypeError: s.year is not a function

      13 |   const s = spacetime([2017, 5, 2]);
      14 |   console.log(s)
    > 15 |   return s.isSame(d2, 'date');
         |            ^
      16 | }

      at Object.year [as day] (node_modules/spacetime/src/methods/same.js:16:15)
      at SpaceTime.isSame (node_modules/spacetime/src/methods/same.js:46:33)
```

Not sure how this broke at all... Hopefully you can fix this soon.

**Comment by spencermountain** [comment]
hey John, it looks like you're using two different input formats, this should work as expected:
```js
const s = spacetime([2017, 5, 2])
console.log(s.isSame([2017, 5, 2], 'millisecond'))
```
cheers
